### ISSUE TITLE
Magic Apiary's don't connect to pipes and doesn't seem to allow for mutations

### ISSUE THREAD

**Issue by perfect007** [MagicBees/MagicBees#102]
I can confirm they don't work with Extra Utilities.  No sides work.  Using version 2.3.2

Not sure if intended but automation is impossible.  Also doesn't display basic info such as why bees are not working, which would be nice (Such as hostile environment ect)

Finally, shift clicking bees in inventory doesn't add them to Apiary.

EDIT: Removed part about mutations not working, as I didn't properly test it.

**Comment by Dlur100** [comment]
I can also confirm that Magic Apiary automation does not work with EnderIO item conduits.  Without automation, these are really not that useful, which is a real shame because I would absolutely love to use them in my Thaumcraft heavy build.  I didn't even bother crafting a Vis Apiary Booster at this point because the Magic Apiary itself seems unfinished.

Also, I can confirm that I cannot shift-click bees into or out of the Magic Apiary.

Using Magic Bees version 2.3.6 on InfiTech 2 3.1.14 modpack.  

I know there are several other people that would love to use Magic Apiaries as part of the modpack I play, but do not because of the automation issue.  

Loving everything else about Magic Bees though!  Thanks!

**Comment by MysteriousAges** [comment]
Thermal Dynamics pipes connect no problem; might have been fixed by #113.
