### ISSUE TITLE
MagicBees v2.4.3 - No specialties being produced

### ISSUE THREAD

**Issue by hypnotizd** [MagicBees/MagicBees#128]
In FTB Infinity Evolved Expert 2.4.1 (Magic Bees v2.4.3) Pyro, Gelid, Winsome, Endearing, Ardite and Cobalt are not producing any specialty resources. These are being housed in Gendustry Industrial Apiary with 8 production upgrades and the bees have Longest Life, Fastest Production speeds.

**Comment by mezz** [comment]
In order to produce their specialty, most bees (all Magic Bees since Forestry 4) require the climate to be *exactly* their favorite.

For instance, Pyro bees need a Hellish and Arid climate to produce their specialty even though they accept climates in a fairly large range.

Testing some to make sure:

![2016-02-27_20 09 16](https://cloud.githubusercontent.com/assets/916092/13377378/3d6795a4-dd8e-11e5-9cb6-d3378ffdc4e6.png)

![2016-02-27_20 15 36](https://cloud.githubusercontent.com/assets/916092/13377392/e3762474-dd8e-11e5-917d-3ace323c6264.png)

![2016-02-27_20 16 53](https://cloud.githubusercontent.com/assets/916092/13377404/5adb65e2-dd8f-11e5-8247-1062204134c4.png)

![2016-02-27_20 17 27](https://cloud.githubusercontent.com/assets/916092/13377405/5cf3e480-dd8f-11e5-9d81-6869522aba95.png)

![2016-02-27_20 34 41](https://cloud.githubusercontent.com/assets/916092/13377478/9348a456-dd91-11e5-9218-f2142ae759c2.png)

**Comment by hypnotizd** [comment]
This is interesting. I submitted this bug report per your suggestion, btw ;-)
https://www.reddit.com/r/feedthebeast/comments/47wutg/bees_broken_in_infinity_241/d0gbxyo

As someone who's used bees since FTB Ultimate 1.4.7, this is quite a surprising change. So now we need to setup multiple locations for bee areas? I guess that clears up this issue/confusion. I'm not sure I like this change, however.

**Comment by mezz** [comment]
Managing the climate is easy to handle with Industrial Apiaries and Alvearies. You need to make sure your bees are as happy as can bee for them to produce their specialty.

**Comment by hypnotizd** [comment]
I see, so using the biome upgrades in the Alvearies or Gendusty machines will make them continue to work as they always have. Well then for a little additional resources/RF to keep them going that works for me. Thanks!

**Comment by mezz** [comment]
Yep! No problem.
